### ISSUE TITLE
The repository contains binaries

### ISSUE THREAD

**Issue by marmistrz** [fabianvdW/FabChess#28]
This was added in https://github.com/fabianvdW/FabChess/commit/35836b0ed58aa57a6a63cf847bf56017b5a8f6d1. Please use the releases for uploading binaries instead.

**Comment by marmistrz** [comment]
@fabianvdW this is about 70M of binaries in the repo that have to be unnecessarily downloaded while cloning the repo. Could you please move the binaries to the releases page?

**Comment by fabianvdW** [comment]
Sorry for being inactive in here. I will move them to the releases.

**Comment by fabianvdW** [comment]
Should be fixed now, I didn't delete it out of git history yet, but that is another problem
