### ISSUE TITLE
FabChess will no longer build under non-x86_64 architectures

### ISSUE THREAD

**Issue by marmistrz** [fabianvdW/FabChess#42]
The culprit is, among others, the following piece of code:
https://github.com/fabianvdW/FabChess/blob/master/core-sdk/src/move_generation/magic.rs#L67-L73
This is a priori a runtime check and the resolution of
```
use std::arch::x86_64::_pext_u64;
```
import will still be attempted (and failed) under non-x86_64 architectures. One should probably create a wrapper for `_pext` which will call `_pext_u64` under x86_64 and emulate it otherwise. Moreover, you may consider having BMI2 instructions as a feature (probably an opt-out one), just as Stockfish does.

I think it'd be a good idea to add a GitHub-Actions-based CI to detect such issues before merging. I recommend checking if the build succeeds under x86_64 and some ARM (say, aarch64) at the very least, possibly something else from [tier 2](https://forge.rust-lang.org/release/platform-support.html)

**Comment by fabianvdW** [comment]
Isn't this easily fixable if I make it a conditional compilation instead of runtime checks to config, like I do [here](https://github.com/fabianvdW/FabChess/blob/755188baf251d2de854c5e6d3a705317393dd0b6/core-sdk/src/move_generation/magic.rs#L22) ?

> Moreover, you may consider having BMI2 instructions as a feature (probably an opt-out one), just as Stockfish does.
I thought one can easily disable target featue?! Isnt it just `-C --target-feature=-bmi2`?
I might just remove PEXT all together for now, I didn't provide a measurable speedup anyway.
> I think it'd be a good idea to add a GitHub-Actions-based CI to detect such issues before merging. I recommend checking if the build succeeds under x86_64 and some ARM (say, aarch64) at the very least, possibly something else from tier 2
I agree, but I do not actually have any experience in this whatsoever. I will do it sometime.

**Comment by marmistrz** [comment]
> Isn't this easily fixable if I make it a conditional compilation instead of runtime checks to config, like I do [here](https://github.com/fabianvdW/FabChess/blob/755188baf251d2de854c5e6d3a705317393dd0b6/core-sdk/src/move_generation/magic.rs#L22) ?

Correct.

> 
> > Moreover, you may consider having BMI2 instructions as a feature (probably an opt-out one), just as Stockfish does.
> 
> I thought one can easily disable target featue?! Isnt it just `-C --target-feature=-bmi2`?
> I might just remove PEXT all together for now, I didn't provide a measurable speedup anyway.
> 

Ouch, my bad. There is a feature guard indeed in the snippet I quoted, I must have missed it.

> > I think it'd be a good idea to add a GitHub-Actions-based CI to detect such issues before merging. I recommend checking if the build succeeds under x86_64 and some ARM (say, aarch64) at the very least, possibly something else from tier 2
> 
> I agree, but I do not actually have any experience in this whatsoever. I will do it sometime.

I'll try to contribute it.

**Comment by fabianvdW** [comment]
Can you confirm it works again in the branch nonx86compilation?

**Comment by marmistrz** [comment]
Yes, it works :)
